resources:
  repositories:
    - repository: qinshift
      type: github
      name: teechMe/qinshift
      endpoint: 'GitHubServiceConnection'
      ref: refs/heads/main

pool:
 vmImage: 'windows-latest'

jobs:
- job: RunTests
  displayName: 'Run Cypress Tests'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'Install dependencies'

    - script: npm run test:ci
      displayName: 'Run tests'
      continueOnError: true
    
    - script: npm run merge-reports
      displayName: 'Merge Reports'
      condition: always()
      
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'cypress\results\merged-results.xml'
        testRunTitle: 'Cypress Tests - $(Build.BuildNumber)'
      condition: succeededOrFailed()
      displayName: 'Publish Test Results'